#!/bin/bash
#
# Write output from tw_cli to a directory

# Config options
SMART_BIN="/usr/sbin/smartctl"
SMART_OUTPUT_DIR="/tmp/smartctl"

# Make sure we can execute tw_cli
if [ ! -x "$SMART_BIN" ]; then
	echo "Error: $SMART_BIN isn't executable"
	exit 3
fi

# If no output dir exists, create it
if [ ! -d "$SMART_OUTPUT_DIR" ]; then
	mkdir $SMART_OUTPUT_DIR
	chmod 755 $SMART_OUTPUT_DIR
fi

for devpath in /dev/sd?; do
	dev=`basename $devpath`
	
	if [ -f "$SMART_OUTPUT_DIR/$dev.ignore" ]; then
		continue
	fi

	$SMART_BIN -A $devpath > "$SMART_OUTPUT_DIR/$dev.tmp"
	if [ $? -eq 0 ]; then
		mv "$SMART_OUTPUT_DIR/$dev.tmp" "$SMART_OUTPUT_DIR/$dev"
	else
		mv "$SMART_OUTPUT_DIR/$dev.tmp" "$SMART_OUTPUT_DIR/$dev.ignore"
	fi
done
