#!/bin/bash
#
# Write output from tw_cli to a directory

# Config options
TW_BIN="/usr/local/bin/tw_cli"
TW_OUTPUT_DIR="/tmp/tw_cli"

# Make sure we can execute tw_cli
if [ ! -x "$TW_BIN" ]; then
	echo "Error: $TW_BIN isn't executable"
	exit 3
fi

# If no output dir exists, create it
if [ ! -d "$TW_OUTPUT_DIR" ]; then
	mkdir $TW_OUTPUT_DIR
	chmod 755 $TW_OUTPUT_DIR
fi

# Grab information about 3ware cards in the chassis
$TW_BIN info > "$TW_OUTPUT_DIR/info"

# Walk each 3ware controller and grab the status
CONTROLLERS=`grep -E "^c" "$TW_OUTPUT_DIR/info" | awk '{print $1}'`
for c in $CONTROLLERS; do
	$TW_BIN info $c unitstatus > "$TW_OUTPUT_DIR/unitstatus_$c"
	$TW_BIN info $c drivestatus > "$TW_OUTPUT_DIR/drivestatus_$c"
done

# New controllers let us walk disk status and SMART
NEW_CONTROLLERS=`grep -E "^c" "$TW_OUTPUT_DIR/info" | grep -v "9500S" | awk '{print $1}'`
for c in $NEW_CONTROLLERS; do
	# Walk every port on this controller and read the drive data out
	PORTS=`grep -E "^p" "$TW_OUTPUT_DIR/drivestatus_$c" | grep -v "NOT-PRESENT" | awk '{print $1}'`
	for p in $PORTS; do
		$TW_BIN /$c/$p show status model firmware serial capacity rasect pohrs temperature lspeed ncq > "$TW_OUTPUT_DIR/drive_${c}_${p}"
	done
done
